### ISSUE TITLE
A Landing Page needed

### ISSUE THREAD

**Issue by inidaname** [Codechamps/OpenPolitics#5]
If anyone is looking for a true community project to contribute to this is the right project, a project that is aimed at bringing transparency and accountability through politics and elections.

Thank You

**Comment by kushalpandya** [comment]
Do we have pages site setup anywhere? or this issue aims to add that? if there are any ideas around how landing page should look, I can open PR to add pages site with the design. :slightly_smiling_face:

**Comment by inidaname** [comment]
@kushalpandya this issue is aimed at that design could be of any intend please if you do have a design go ahead and open the PR
